"""remove_guest_fields

Revision ID: f8f76f298f64
Revises: 0313329943af
Create Date: 2026-09-04 00:50:08.179036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8f76f298f64'
down_revision: Union[str, Sequence[str], None] = '0313329943af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_players', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('match_players', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_match_user', 'match_players', ['match_id', 'user_id'])
    op.drop_constraint(op.f('match_players_registered_by_fkey'), 'match_players', type_='foreignkey')
    op.drop_column('match_players', 'registered_by')
    op.drop_column('match_players', 'guest_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_players', sa.Column('guest_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('match_players', sa.Column('registered_by', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('match_players_registered_by_fkey'), 'match_players', 'users', ['registered_by'], ['telegram_id'])
    op.drop_constraint('uq_match_user', 'match_players', type_='unique')
    op.alter_column('match_players', 'joined_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('match_players', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
